### ISSUE TITLE
Wide character in query

### ISSUE THREAD

**Issue by dan-zeman** [ufal/perl-pmltq-web#38]
In the new interface, in UD Czech, I tried the following query (not the "š" character in it):

a-node $a := [lemma = "všechen"] >> for lower($a.form), $a.tag give $1, $2, count() sort by $1

and got an error as a result:

INTERNAL SERVER ERROR: Wide character in subroutine entry at /opt/pmltq-server/releases/20150824144132/script/../lib/PMLTQ/Server/Model/History.pm line 20, <DATA> line 223.

**Comment by dan-zeman** [comment]
(BTW, this is probably unrelated but I cannot reproduce the query here; with another query, the page hung up when I tried to edit the query and pressed the backspace key (I think there was something like form="ten" and I was just about to erase the final quotation mark.)

**Comment by dan-zeman** [comment]
I just tried and found out that the above query still has problems. There is no longer an INTERNAL SERVER ERROR; however, the server simply says "Error while executing query."

http://hdl.handle.net/11346/PMLTQ-IODA

**Comment by Ansa211** [comment]
I found out that the problem only appears when I am logged in (via Shibboleth). It happens both in Chromium and in Firefox.

**Comment by dan-zeman** [comment]
Hypothesis: the bug is somehow related to history tracking, perhaps to saving Unicode strings from Perl to the database. Evidence:

- The first exception I encountered (see above) was in the History module.
- @Ansa211 has also problems with lists of saved queries.
- When you are not logged in, presumably no history of queries is maintained for you?
- I think the history function was out of order for some time, until @matyaskopp launched it again. That could explain why I was thinking that the bug had been fixed already. Otherwise I believe I would be hitting it frequently :-)

**Comment by matyaskopp** [comment]
fixed with: https://github.com/ufal/perl-pmltq-server/commit/b03f146235de2271bd365bb362e46a56cf508bd1

**Comment by jonathanverner** [comment]
(comment by @Ansa211) I still have problems saving this query to a list: http://hdl.handle.net/11346/PMLTQ-LIRF

**Comment by matyaskopp** [comment]
Putting this to history works but not to other query list. You are right

**Comment by matyaskopp** [comment]
fixed with https://github.com/ufal/perl-pmltq-server/commit/f7dfc342a3cd6ef82a8aef079d69c5af34882622
